build.gradle, gradle.properties, java-sdk/build.gradle, samples/build.gradle
Implement publishing to Maven Central
Also optimize build scripts
=> TNT-33910 Implement publishing to Maven Central

java-sdk/build.gradle, java-sdk/src/main/java/com/adobe/target/edge/client/ondevice/OnDeviceDecisioningService.java, java-sdk/src/test/java/com/adobe/target/edge/client/ondevice/DefaultRuleLoaderTest.java
Gradle build clean up and some dependencies upgrades
Gradle build clean up and some dependencies upgrades
None
Preparing for release
None
None
=> Build cleanup and deps updates

.github/workflows/gradle-ci.yml
Adding CI github action for Gradle
Adding CI github action for Gradle
None
First stab at adding CI GitHub Action for Gradle Build
=> Adding CI github action for Gradle

CHANGELOG.md
=> TNT-38512 Add a link to ODD docs

src/main/java/com/adobe/target/edge/client/TargetClient.java
Fixing Javadoc for TargetClient
Fixing Javadoc for TargetClient
None
The publishing workflow is failing because of incorrect Javadoc for TargetClient
It was tested by running `./gradlew javadoc`
=> Fixing Javadoc for TargetClient

.github/workflows/gradle-publishing.yml, build.gradle
Adding GPG signing details
Adding GPG signing details
None
Maven Central requires arifact signing this PR is an attempt to add al the necessary env vars so Gradle signing plugin could work as expected
=> Adding GPG signing details

src/main/java/com/adobe/target/edge/client/model/TargetAttributesResponse.java
`TargetAttributesResponse` should be effectively immutable
`TargetAttributesResponse` should be effectively immutable
None
`TargetAttributesResponse` should be effectively immutable
Unit tests
=> TNT-38893 - ensure attributes response is unmodifiable

CHANGELOG.md, build.gradle, gradle.properties
Upgrading ECID service dependency
Upgrading ECID service dependency
None
Upgrading ECID service dependency
Running a full build
=> Upgrading ECID service dependency

CHANGELOG.md, gradle.properties
Increasing release version
Increasing release version
None
Increasing release version
=> Increasing release version

CHANGELOG.md, gradle.properties, src/main/java/com/adobe/target/edge/client/utils/CookieUtils.java, src/main/java/com/adobe/target/edge/client/utils/TargetConstants.java
Fix incorrect MaxAge set in response cookies
https://jira.corp.adobe.com/browse/TNT-40895
=> TNT-40895 Fix incorrect MaxAge set in response cookies

src/main/java/com/adobe/target/edge/client/DefaultTargetClient.java, src/main/java/com/adobe/target/edge/client/ondevice/OnDeviceDecisioningService.java, src/main/java/com/adobe/target/edge/client/ondevice/OnDeviceDecisioningServicesManager.java, src/main/java/com/adobe/target/edge/client/service/DefaultTargetService.java, src/main/java/com/adobe/target/edge/client/service/NotificationService.java, src/main/java/com/adobe/target/edge/client/service/TelemetryService.java, src/test/java/com/adobe/target/edge/client/entities/TargetDeliveryAttributesTest.java, src/test/java/com/adobe/target/edge/client/entities/TargetDeliveryExceptionTest.java, src/test/java/com/adobe/target/edge/client/entities/TargetDeliveryLocalGeoTest.java, src/test/java/com/adobe/target/edge/client/entities/TargetDeliveryLocalPropertyTest.java, src/test/java/com/adobe/target/edge/client/entities/TargetDeliveryRequestLocalMboxTest.java, src/test/java/com/adobe/target/edge/client/entities/TargetDeliveryRequestLocalViewTest.java, src/test/java/com/adobe/target/edge/client/entities/TargetDeliveryRequestTest.java, src/test/java/com/adobe/target/edge/client/service/NotificationServiceTest.java, src/test/java/com/adobe/target/edge/client/service/TelemetryServiceTest.java, src/test/java/com/adobe/target/edge/client/utils/TargetTestDeliveryRequestUtils.java
Add other telemetry features & remove delivery api duplicate code
Packaged into jar file & tested in client sample JavaSDK
=> TNT-42403-Add other telemetry features

src/main/java/com/adobe/target/edge/client/http/DefaultTargetHttpClient.java, src/main/java/com/adobe/target/edge/client/http/ResponseWrapper.java, src/main/java/com/adobe/target/edge/client/http/TargetHttpClient.java, src/main/java/com/adobe/target/edge/client/http/TargetHttpClientLoggingDecorator.java, src/main/java/com/adobe/target/edge/client/service/DefaultTargetService.java, src/main/java/com/adobe/target/edge/client/service/TelemetryService.java, src/main/java/com/adobe/target/edge/client/utils/MathUtils.java, src/test/java/com/adobe/target/edge/client/service/TelemetryServiceTest.java, src/test/java/com/adobe/target/edge/client/utils/TargetTestDeliveryRequestUtils.java
Collect response parsing time metric & response size
Packaged into jar & looked into telemetry inside the sample app
=> Tnt-42404- Calculate & capture parsing time & response Size

src/test/java/com/adobe/target/edge/client/http/DefaultTargetHttpClientTest.java, src/test/java/com/adobe/target/edge/client/service/DefaultTargetServiceTest.java, src/test/java/com/adobe/target/edge/client/utils/MockRawResponse.java, src/test/java/com/adobe/target/edge/client/utils/TargetTestDeliveryRequestUtils.java
Unit test coverage for private method call
=> [TNT-42930]test callToDeliveryApi private method for both sync n async

src/main/java/com/adobe/target/edge/client/service/TelemetryService.java, src/test/java/com/adobe/target/edge/client/service/TelemetryServiceTest.java
Added telemetryServerToken
https://jira.corp.adobe.com/browse/TNT-42980
=> [TNT-42980] added telemetryServerToken

CHANGELOG.md, gradle.properties
Gradle version 2.2.0 with change log
=> release readiness v2.2.0

src/main/java/com/adobe/target/edge/client/service/TelemetryService.java, src/test/java/com/adobe/target/edge/client/service/TelemetryServiceTest.java
Logic for determining executionMode
Packaged the jar file & tested all the use cases in the sample code
=> TNT-43749-executionMode fix

CHANGELOG.md, gradle.properties, src/main/java/com/adobe/target/edge/client/utils/TargetConstants.java
Release readiness with v2.2.1
This release has fixes related to [TNT-43749](https://jira.corp.adobe.com/browse/TNT-43749) and [TNT-43530](https://jira.corp.adobe.com/browse/TNT-43530)
=> bug fixing with release version v2.2.1

README.md
=> use newer published version

CHANGELOG.md, README.md, build.gradle, gradle.properties, src/main/java/com/adobe/target/delivery/v1/model/Context.java, src/main/java/com/adobe/target/edge/client/utils/TargetConstants.java
Update ECID-service to v1.0.3 in order to fix NFE in parsing expiry values from AMCV cookie
Note: @shandilya3 - this PR also reverts the change from #57 adding support for ClientHints in the Context Delivery request DTO, as we can't release it until support for ClientHints has been released on the Target edge. We will need to re-apply this change in the upcoming v2.2.3 SDK release adding support for ClientHints.
https://jira.corp.adobe.com/browse/TNT-43949
Update ECID-service to v1.0.3 in order to fix NFE in parsing expiry values from AMCV cookie
=> TNT-43949 Update ECID-service to fix NFE in parsing expiry values from AMCV cookie

src/main/java/com/adobe/target/edge/client/ondevice/collator/UserParamsCollator.java, src/test/java/com/adobe/target/edge/client/ondevice/collator/UserParamsCollatorTest.java
This PR adds support for client hints.
This will be tested thoroughly once we have backend system ready to support. This pr will be merged only after testing.
=> Tnt-43818 odd client hints inclusion

CHANGELOG.md, gradle.properties, src/main/java/com/adobe/target/edge/client/utils/TargetConstants.java
=> Release readiness v2.3.0

src/main/java/com/adobe/target/edge/client/service/DefaultTargetService.java
=> TNT-39914 changing sticky hint to always update from Delivery API response regardless of current Decisioning method

src/main/java/com/adobe/target/edge/client/ondevice/collator/CustomParamsCollator.java, src/test/java/com/adobe/target/edge/client/entities/TargetDeliveryRequestLocalMboxTest.java, src/test/java/com/adobe/target/edge/client/ondevice/collator/CustomParamsCollatorTest.java, src/test/java/com/adobe/target/edge/client/ondevice/collator/UserParamsCollatorTest.java, src/test/resources/DECISIONING_PAYLOAD_PARAMS.json
Customer created rules that contain dot notation (`ex: favorite.color`) are now transformed into nested JSON objects so that they can be correctly processed by JsonLogic.
=> TNT-45549 creating nested json objects for custom rules with dot notation

CHANGELOG.md, gradle.properties, src/main/java/com/adobe/target/edge/client/utils/TargetConstants.java
- Client custom Mbox parameters now correctly support dot notation
- stickyLocationHint is updated regardless of Decisioning method
=> Release 2.3.1

CHANGELOG.md, gradle.properties
- Custom HTTP client support to Client configuration
- Additional support for complex domain parsing
- SDK version no longer set in source code
=> Release 2.4.0

CHANGELOG.md, gradle.properties
=> release 2.5.1

src/main/java/com/adobe/target/edge/client/ondevice/DefaultRuleLoader.java
=> TNT-49117-  log the root cause of the exception

README.md, codegeneration/codegen.sh, src/main/java/com/adobe/target/edge/client/ondevice/DefaultRuleLoader.java
- Fix documentation link in README
- Remove confusing code comments
- Add comment explaining openapi codegen script
=> update README and other documentation changes

build.gradle, src/test/java/com/adobe/target/edge/client/ondevice/DefaultRuleLoaderTest.java, src/test/java/com/adobe/target/edge/client/utils/MockRawResponse.java, src/test/java/com/adobe/target/edge/client/utils/TargetTestDeliveryRequestUtils.java
=> [TNT-49982] upgrade unirest-java

README.md
=> [no-jira] - update readme to include test command
